server:
  port: 8445
logging:
  file: /java/OCP_LOGS/smart-auth/smart-auth.log
info:
  component: Omnibus Care Plan - SMART Authorization
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ReadTimeout: 50000
spring:
  redis:
    host: dockerhost
