server:
  port: 8445
logging:
  file: /java/OCP_LOGS/smart-auth/smart-auth.log
info:
  component: Omnibus Care Plan - SMART Authorization
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ReadTimeout: 50000
spring:
  redis:
    host: dockerhost
smart-auth:
  context-initializer: http://localhost:3000/ocp-ui/smart-context
  oauth2: http://localhost:8080/uaa
  oauth2-authorize: ${smart-auth.oauth2}/oauth/authorize
  oauth2-token: ${smart-auth.oauth2}/oauth/token
