server:
  port: 8445
logging:
  file: /java/OCP_LOGS/smart-auth/smart-auth.log
info:
  component: Omnibus Care Plan - SMART Authorization
hystrix.command.default.execution.timeout.enabled: false
ribbon:
  ReadTimeout: 50000
spring:
  redis:
    host: dockerhost
smart-auth:
  context-initializers:
    user: http://localhost:3000/ocp-ui/smartLogin
    organization: http://localhost:3000/ocp-ui/organizationPicker
    location: http://localhost:3000/ocp-ui/locationPicker
    patient: http://localhost:3000/ocp-ui/patientPicker
    encounter: http://localhost:3000/ocp-ui/encounterPicker
    resource: http://localhost:3000/ocp-ui/resourcePicker
